// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGAt00X0D2YEqJD-gEMb-LCyxJdL9PPQo',
    appId: '1:129912486768:web:bf250d2f9879d3d120adb5',
    messagingSenderId: '129912486768',
    projectId: 'rentawayapp-8e4ad',
    authDomain: 'rentawayapp-8e4ad.firebaseapp.com',
    storageBucket: 'rentawayapp-8e4ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDreD4ejapalMvoes2CCW2uIRsZhTQkeh4',
    appId: '1:129912486768:android:ce84a1e2b752d52f20adb5',
    messagingSenderId: '129912486768',
    projectId: 'rentawayapp-8e4ad',
    storageBucket: 'rentawayapp-8e4ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpSxrZ3Vp5trzUSI8Zx-pvqr3ak7il6x0',
    appId: '1:129912486768:ios:cec70fed196ce99020adb5',
    messagingSenderId: '129912486768',
    projectId: 'rentawayapp-8e4ad',
    storageBucket: 'rentawayapp-8e4ad.appspot.com',
    iosBundleId: 'com.example.rentawayapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpSxrZ3Vp5trzUSI8Zx-pvqr3ak7il6x0',
    appId: '1:129912486768:ios:a3bd6a346337dbba20adb5',
    messagingSenderId: '129912486768',
    projectId: 'rentawayapp-8e4ad',
    storageBucket: 'rentawayapp-8e4ad.appspot.com',
    iosBundleId: 'com.example.rentawayapp.RunnerTests',
  );
}
